require: rubocop-rspec
AllCops:
  TargetRubyVersion: 2.5.3
  Include:
    - Rakefile
    - app/**/*.rb
    - spec/**/*.rb
    - config/**/*.rb
    - lib/**/*.rb
  Exclude:
    - db/**/*
    - script/**/*
    - bin/**/*
    - vendor/**/*
Metrics/LineLength:
  Enabled: true
  Max: 150
Style/Documentation:
  Enabled: false
Layout/AlignParameters:
  Enabled: false
Metrics/MethodLength:
  Max: 30
Style/AndOr:
  Enabled: false
Metrics/ModuleLength:
  Max: 200
Metrics/ClassLength:
  Max: 200
Style/ClassAndModuleChildren:
  Enabled: false
Layout/MultilineOperationIndentation:
  Enabled: false
Metrics/AbcSize:
  Max: 20
Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    default: ()
    '%r': '{}'
    '%w': '()'
    '%W': '()'
    '%i': '()'
    '%I': '()'
Style/FrozenStringLiteralComment:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - spec/**/*
    - config/**/*
Style/FormatStringToken:
  EnforcedStyle: template
